# -*- coding: utf-8 -*-
"""load

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tgDbaQvaZqqvnTMZKT7UMbDxXMHGKr1
"""



"""import os
import pandas as pd
from google.cloud import bigquery
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Set up credentials and project info
project_id = os.getenv("GCP_PROJECT_ID")
dataset_id = os.getenv("BQ_DATASET_NAME")
table_name = "stock_data"  # Change to your table name
excel_file_path = "your_excel_file.xlsx"  # Change to your file

# Initialize BigQuery client
client = bigquery.Client()

# Read Excel file
df = pd.read_excel(excel_file_path)

# Define full table ID
table_id = f"{project_id}.{dataset_id}.{table_name}"

# Load to BigQuery
job = client.load_table_from_dataframe(df, table_id)
job.result()  # Wait for the job to finish

print(f"✅ Loaded {job.output_rows} rows to {table_id}")

"""