# -*- coding: utf-8 -*-
"""upload_to_azure.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z3cCopySGzPfyfDp9ZgMaij-lPJjUmKy
"""



"""from azure.storage.blob import BlobServiceClient
import os

def upload_to_azure(local_file_path, container_name, blob_name, connection_string):
    # Connect to Azure Blob Service
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    
    # Get container client
    container_client = blob_service_client.get_container_client(container_name)
    
    # Upload the file
    with open(local_file_path, "rb") as data:
        container_client.upload_blob(name=blob_name, data=data, overwrite=True)
    
    print(f"Uploaded {blob_name} to Azure container {container_name}")

# Example usage
if __name__ == "__main__":
    connection_string = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
    upload_to_azure(
        local_file_path="AAPL_stock.csv",
        container_name="raw-stock-data",
        blob_name="AAPL_stock.csv",
        connection_string=connection_string
    )

"""